### ISSUE TITLE
error: Missing parameter market

### ISSUE THREAD

**Issue by nuryagdym** [vdbelt/ftx-php#1]
Hi,
I am trying to place a market order but I am getting the "Missing parameter market" error. 
I tried both ways as described in the documentation but returning the same error.
I tried to find the problem by myself but no luck.
`
1. $response = $ftx->orders()->create()->buy('BTC-PERP')->market(1)->place();
2. $response = $ftx->orders()->create(['market' => 'BTC-PERP', 'type' => 'market', 'size' => 1])->place();`

Can you please help. 
Thanks in advance

**Comment by vdbelt** [comment]
Thanks for reporting.

This should have been fixed now (dev-master). 

Note that this library is still work in progress. Feel free to open another issue if you have feedback or want to report something else.

**Comment by nuryagdym** [comment]
Thank you, it is working now.
My stupid ass, I tried to set Content-type header as you did but I did wrong :).
Instead of:
`$request = $request->withHeader('Content-Type', 'application/json');`
I tried this way:
`$request->withHeader('Content-Type', 'application/json');`
