### ISSUE TITLE
depositAddress could not delivery method.

### ISSUE THREAD

**Issue by dreamwalter** [vdbelt/ftx-php#12]
$ftx->wallet()->depositAddress('USDT') just show method: omni.
I changed the depositAddress function in Wallet.php as following.

    public function depositAddress(string $coin, string $method = "")
    {
      if (empty($method))
        return $this->respond($this->http->get(self::WALLET_DEPOSIT_ADDRESS_URI.'/'.$coin));
      else {
        return $this->respond($this->http->get(self::WALLET_DEPOSIT_ADDRESS_URI.'/'.$coin.'?method='.$method));
      }
    }

example.php
    print_r($ftx->wallet()->depositAddress('USDT','trx'))

It seems not working.  Could you help me?

**Comment by dreamwalter** [comment]
public function depositAddress(string $coin, ?string $method = null)  {
    return $this->respond($this->http->get(self::WALLET_DEPOSIT_ADDRESS_URI.'/'.$coin, compact('method')));
}
It seems okay after checking.

**Comment by vdbelt** [comment]
Thanks! I have tagged a new [release](https://github.com/vdbelt/ftx-php/releases/tag/v0.1.6) with this functionality.
