### ISSUE TITLE
Not logged in

### ISSUE THREAD

**Issue by pfergi42** [vdbelt/ftx-php#13]
Hello, I can correctly instantiate the FTX object and get the price like this:

```
// Authenticate
$ftx = FTX::create($api_key, $api_secret);

$btc_usd_market_data = $ftx->markets()->get('BTC/USD');
$price = $btc_usd_market_data['result']['price'];
```

However, when I try to use any other endpoints like orders(), history() or onSubaccount() I get a Fatal PHP error saying **Not logged in**:

_PHP Fatal error:  Uncaught FTX\Client\Exceptions\UnauthorizedException: Not logged in_

Example code causing the problem:
```
// Authenticate
$ftx = FTX::create($api_key, $api_secret);

$accounts = $ftx->account()->get();
print_r($accounts);
```

Great wrapper here for the FTX API, thank you in advance!

**Comment by pfergi42** [comment]
And I just realized, when I change one character in the API key in the first example, it still works. So I must not be authenticating correctly, or the FTX object is being created without Authentication, and the markets() still works without API keys.

So it appears something is wrong with the authentication...

**Comment by vdbelt** [comment]
Can you confirm you created the keys on ftx.com?

It could also be a timestamp issue ([see last paragraph](https://blog.ftx.com/blog/api-authentication/)).

> If you ever encounter a Not logged in error it means that authentication failed. In this case make sure that your code is correct by referring to the above example and also check your timestamp against our server’s timestamp using this endpoint https://otc.ftx.com/api/time

**Comment by pfergi42** [comment]
Ah actually my keys are from FTX.US.

That could explain it. I tried changing the BASE_URI inside FTX.php to the following:

`const BASE_URI = 'https://ftx.us/api';`

But still getting the same error. Perhaps there are other places to change the BASE_URI? Will this code work with FTX.US?

**Comment by vdbelt** [comment]
I believe the following header names need to be replaced from `FTX` to `FTXUS` (eg. `FTXUS-KEY`) as well:
https://github.com/vdbelt/ftx-php/blob/1bc0aabbef297b82289aa1afad05df5c4d98d722/src/Client/HttpClient.php#L109-L111

I would welcome a PR that easily lets you switch between .com and .us

Otherwise, you can check out https://github.com/jjpost86/ftxus-php, which currently provides a wrapper around this package for usage with ftx.us.

**Comment by pfergi42** [comment]
Hello @vdbelt, that did the trick! Thank you so much.

I also had to update FTX --> FTXUS on the SUBACCOUNT header on line 103:

`$request = $request->withHeader('FTXUS-SUBACCOUNT', $this->subaccount);`

Now it seems to be working. I'll see if I can manage a pull request. Great work on this fabulous contribution.
