### ISSUE TITLE
Query paramaters are not taken into account for the auth signature

### ISSUE THREAD

**Issue by booni3** [vdbelt/ftx-php#21]
i.e.

```
GET /orders?market={market}
```

In this example, the signature is generated from `/orders` but it must take into account the full path including query string `orders?market=BTC-PERP`

Would you be happy with something like this?

```php
protected function signature(){
    $this->path='/api'.$this->path;

    if($this->authorization===true){
        $temp=$this->nonce.$this->type.$this->path;
        if($this->type!='POST'){
            if(!empty($this->data)) $temp.='?'.http_build_query($this->data);
        } else {
            if(!empty($this->data)) $temp.=json_encode($this->data);
        }
        //echo $temp.PHP_EOL;
        $this->signature = hash_hmac('sha256', $temp, $this->secret);
    }
}
```

I am just highlighting the issue for now. When I get around to needing this function, I will look to add a PR (if it has not been actioned already)

**Comment by vdbelt** [comment]
The query parameters are already taken into account. See https://github.com/vdbelt/ftx-php/blob/9b5828fb3e9ef472ec9b13fb9cf1daf4ab77b933/src/Client/HttpClient.php#L122

Feel free to reopen this issue if there is something you can't get to work.
