### ISSUE TITLE
Orders

### ISSUE THREAD

**Issue by bulbozavr13** [vdbelt/ftx-php#4]
I can’t create an order, writes  "Missing parameter market"

**Comment by vdbelt** [comment]
Can you share your code?

**Comment by bulbozavr13** [comment]
`require('../vendor/autoload.php');

use FTX\FTX;


$ftx = FTX::create('key', 'secret');

$res=$ftx->orders()->create()->buy('BEAR/USD')->limit(1, 4000)->place();
var_dump($res);`

**Comment by vdbelt** [comment]
Thanks. 

It was fixed already, but the fixes weren't released yet. I have tagged a new release, so a `composer update` should do it.
