### ISSUE TITLE
Issue setting up

### ISSUE THREAD

**Issue by vlavani** [vdbelt/ftx-php#5]
When i run ` composer require vdbelt/ftx-php php-http/curl-client nyh                                                                                                                                 olm/psr7`

I get his error: ` Package vdbelt/ftx-php has a PHP requirement incompatible with your PHP version, PHP extensions and Com
  poser version
`
 Any suggestions ?

**Comment by vdbelt** [comment]
This package has a minimum requirement of PHP 7.4. Which version are you using?
